Rebranded to CompuGuessr and implemented FastCGI protocol and tests

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,5 +1,5 @@
 
-name: naws CI
+name: Test
 
 on:
   push:
@@ -14,29 +14,28 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-  tests:
+  build-and-test:
     runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-      - name: Install dependencies
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y nasm build-essential mold valgrind
-      - name: Install Hurl
-        uses: gacts/install-hurl@v1
-      - name: Build server
-        run: |
-          sh build.sh
-          chmod +x naws
-      - name: Valgrind and Hurl
-        run: |
-          valgrind --leak-check=full --error-exitcode=1 ./naws &
-          NAWS_PID=$!
-          sleep 2
-          hurl --test test/integration.hurl
-          HURL_EXIT=$?
-          kill -SIGTERM $NAWS_PID || true
-          wait $NAWS_PID || true
-          exit $HURL_EXIT
 
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v4
+
+    - name: Install dependencies
+      run: |
+        sudo apt-get update
+        sudo apt-get install -y clang gcc make mold nasm python3
+
+    - name: Compile
+      run: make debug
+
+    - name: Run tests
+      run: python3 tests/test_fcgi.py
+
+    - name: Verify build artifacts
+      run: |
+        if [ ! -f bin/debug/compuguessr ]; then
+          echo "Binary not found!"
+          exit 1
+        fi
+        echo "Build and tests are successful."
